---
# Usage:
# $ ansible-playbook books/install_app.yml -e @myapp.yml
- hosts: localhost
  roles:
  - "ansible-bonita-provisioning"

- hosts: localhost
  # All vars comes from the var file
  tasks:
  - name: Login to Bonita
    #   bonita session [login <url> <username> <password>|logout|get]
    bonita:
      args: 
        session: yes
        login: yes
        "<url>": "{{ bonita_url }}"
        "<username>": "{{ bonita_credentials.login }}"
        "<password>": "{{ bonita_credentials.password }}"
      verbose: yes
  - name: Get session
    bonita:
      args:
        session: yes
        get: yes
    register: session_raw
  - name: Display session
    debug:
      msg: "{{ session_raw['result']['datas'] }}"
  - name: Upload the processes
    debug:
      msg: "{{ processes }}"
#  - name: Deploy the processes
#    debug:
#      msg: "{{ processes }}"
#  - name: Activate the main process
#    debug:
#      msg: "{{ main_process }}"
  - name: Logout
    bonita:
      args:
        session: yes
        logout: yes
